# Generated by Django 5.2.17 on 2026-09-24 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('is_open', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=100)),
                ('name_key', models.CharField(max_length=64)),
                ('identity_cipher', models.TextField()),
                ('identity_key', models.CharField(max_length=64)),
                ('class_name', models.CharField(max_length=50)),
                ('original_phone_cipher', models.TextField(blank=True)),
                ('current_phone_cipher', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', '未开始'), ('draft', '核对中'), ('submitted', '已确认')], default='new', max_length=16)),
                ('phone_issue', models.BooleanField(default=False)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='delaycheck.batch')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('phone_cipher', models.TextField()),
                ('issue', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='delaycheck.student')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('student', 'version'), name='unique_yanchi_submission')],
            },
        ),
    ]
