# Generated by Django 5.2.17 on 2026-09-11 10:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor', models.CharField(max_length=100, verbose_name='操作人')),
                ('action', models.CharField(max_length=100, verbose_name='操作')),
                ('target', models.CharField(max_length=100, verbose_name='对象')),
                ('detail_cipher', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='时间')),
            ],
            options={
                'verbose_name': '操作记录',
                'verbose_name_plural': '操作记录',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Throttle',
            fields=[
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('count', models.PositiveIntegerField(default=0)),
                ('started_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='批次名称')),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='导入时间')),
                ('active', models.BooleanField(default=False, verbose_name='当前批次')),
                ('is_open', models.BooleanField(default=True, verbose_name='开放家长核对')),
                ('demo', models.BooleanField(default=False, verbose_name='虚构演示数据')),
            ],
            options={
                'verbose_name': '导入批次',
                'verbose_name_plural': '导入批次',
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('active',), name='one_active_batch')],
            },
        ),
        migrations.CreateModel(
            name='ImportPreview',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fingerprint', models.CharField(max_length=64)),
                ('payload_cipher', models.TextField()),
                ('title', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_row', models.PositiveIntegerField()),
                ('serial_hash', models.CharField(max_length=64)),
                ('identity_hash', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('class_name', models.CharField(blank=True, max_length=100, verbose_name='班级')),
                ('original_cipher', models.TextField()),
                ('school_cipher', models.TextField(blank=True)),
                ('draft_cipher', models.TextField(blank=True)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('new', '未开始'), ('draft', '核对中'), ('submitted', '已提交')], default='new', max_length=16, verbose_name='核对状态')),
                ('has_issue', models.BooleanField(default=False, verbose_name='学校待处理')),
                ('change_count', models.PositiveIntegerField(default=0, verbose_name='更正项数')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='提交时间')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='checks.batch')),
            ],
            options={
                'verbose_name': '学生',
                'verbose_name_plural': '学生',
                'ordering': ['source_row'],
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='提交版本')),
                ('payload_cipher', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='checks.student')),
            ],
            options={
                'verbose_name': '提交历史',
                'verbose_name_plural': '提交历史',
            },
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('batch', 'serial_hash'), name='unique_batch_serial'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('batch', 'identity_hash'), name='unique_batch_identity'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('student', 'version'), name='unique_submission_version'),
        ),
    ]
